# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uf4sBMXecbEBA4eD5QCYt27JgN2Viy36
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load data
data = pd.read_csv("amr_data.csv")

print("Preview:")
print(data.head())

# -------------------
# Overall Resistance
# -------------------
counts = data['result'].value_counts()

counts.plot(kind='bar')
plt.title("Overall Resistance Distribution")
plt.xlabel("Result")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

# -------------------
# Antibiotic Resistance
# -------------------
resistance = data[data['result'] == 'R'].groupby('antibiotic').size()

resistance.plot(kind='bar')
plt.title("Resistance per Antibiotic")
plt.xlabel("Antibiotic")
plt.ylabel("Resistant Count")
plt.xticks(rotation=45)
plt.show()

# -------------------
# ESBL Distribution
# -------------------
esbl = data['ESBL'].value_counts()

esbl.plot(kind='bar')
plt.title("ESBL vs Non-ESBL")
plt.xlabel("Category")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

# -------------------
# ESBL vs Antibiotic
# -------------------
cross = pd.crosstab(data['antibiotic'], data['ESBL'])

cross.plot(kind='bar', stacked=True)
plt.title("Antibiotic vs ESBL")
plt.xlabel("Antibiotic")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()